Repository cidgoh/nf-ncov-voc, pull requests merged in 2021-10, with the labels that each got.

#15 User uploaded data (vcf, tsv, fasta)
  main.nf
  workflows/covidmvp_user.nf
Labels: enhancement

#22 Updating single genome option & stable version of DSL=2 in COVID MVP
  modules/custom.nf
  modules/freebayes.nf
  workflows/covidmvp.nf
Labels: enhancement, Wip

#25 Updating modules to reflect consistent filenames and tags
  modules/bbmap_reformat.nf
  modules/bcftools.nf
  modules/bwaindex.nf
  modules/bwamem.nf
  modules/help.nf
  modules/ivar.nf
  modules/minimap2.nf
  modules/seqkit.nf
  modules/snpeff.nf
Labels: reproducibility

#39 Updating Documentation
  README.md
  figs/COVIDMVP.drawio.png
Labels: documentation, enhancement

#35 clade_defining status based on threshold
  bin/gvf2tsv.py
  bin/vcf2gvf.py
Labels: enhancement

#48 Update variants 2021-10-29
  .github/data/variants/variants_who.tsv
Labels: documentation
