Repository cidgoh/nf-ncov-voc, pull requests merged in 2022-01, with the labels that each got.

#75 Update variants_who.tsv
  .github/data/variants/variants_who.tsv
Labels: documentation

#77 'sample_collection_date' based filtering enabled in extract_metadata.py
  bin/extract_metadata.py
Labels: bug

#79 Restructured modules to allow nf-core modules
  modules/local/bbmap_reformat.nf
  modules/local/bcftools.nf
  modules/local/bwaindex.nf
  modules/local/bwamem.nf
  modules/local/custom.nf
  modules/local/freebayes.nf
  modules/local/header.nf
  modules/local/help.nf
  modules/local/ivar.nf
  modules/local/minimap2.nf
  modules/local/seqkit.nf
  modules/local/seqkitstats.nf
  modules/local/seqtk.nf
  modules/local/snpeff.nf
  modules/local/wf_header.nf
Labels: reproducibility

#80 Integrating pangolin module from nf-core
  bin/merge_pangolin_metadata.py
  modules.json
  modules/nf-core/modules/pangolin/main.nf
  modules/nf-core/modules/pangolin/meta.yml
Labels: enhancement

#82 Restructured required files
  .github/data/clade_defining/clade_defining_mutations.tsv
  assets/logo/LogoCIDGOH1.png
  assets/ncov_functionalAnnotation/functional_annotation_V.0.4.tsv
  assets/ncov_geneCoordinates/gene_positions.json
  assets/ncov_genomeAnnotation/GCF_009858895.2_ASM985889v3_genomic.gff
  assets/ncov_genomeFeatures/MN908947.3.gff3
  assets/ncov_multiNames/mutation_names_to_split.tsv
  assets/ncov_problematicSites/problematic_sites_sarsCov2.vcf
  assets/ncov_refdb/MN908947.3.fasta
  assets/ncov_refdb/MN908947.3.fasta.amb
  assets/ncov_refdb/MN908947.3.fasta.ann
  assets/ncov_refdb/MN908947.3.fasta.bwt
  assets/ncov_refdb/MN908947.3.fasta.fai
  assets/ncov_refdb/MN908947.3.fasta.pac
  assets/ncov_refdb/MN908947.3.fasta.sa
  assets/ncov_surveillanceIndicators/functions_df_template.tsv
  assets/ncov_variants/variants_who.tsv
Labels: reproducibility, design

#83 Updated scripts for reproducibility
  bin/extract_metadata.py
  bin/functional_annotation.py
  bin/gvf2tsv.py
  bin/map_virusseq_GISAID.py
  bin/mature_peptide_annotation.py
  bin/merge_pangolin_metadata.py
  bin/parse_variants.py
  bin/problematic_sites_tag.py
  bin/process_gvcf.py
  bin/vcf2gvf.py
Labels: documentation, reproducibility, design

#85 New Feature: Summarized Surveillance report - PDF
  bin/surveillance_report_Alpha.tsv
  bin/surveillance_report_pdf.py
  modules/local/custom.nf
Labels: enhancement, design

#86 Restructured workflows for better integration with different file formats
  main.nf
  workflows/covidmvp.nf
  workflows/covidmvp_annotation.nf
  workflows/covidmvp_preprocessing.nf
  workflows/covidmvp_surveillance.nf
  workflows/covidmvp_variantcalling.nf
Labels: reproducibility, design

#87 Updated dataflow workflow for nf-ncov-voc
  figs/COVIDMVP.drawio.png
Labels: documentation, design

#88 Updating bits and pieces
  .gitignore
  bin/surveillancereportdfs.py
  util/surveillancereportdfs.py
  workflows/covidmvp_user.nf
Labels: Work in progess

#89 Update .gitignore
  .gitignore
Labels: documentation

#90 change to allow user-uploaded files
  bin/gvf2tsv.py
Labels: bug

#91 Updating structure for mode=user to produce surveillance reports for user uploaded files through covidmvp
  assets/logo/LogoCIDGOH1.png
  bin/gvf2tsv.py
  bin/surveillance_report_pdf.py
  main.nf
  modules/local/custom.nf
  util/surveillancereportdfs.py
  workflows/covidmvp_surveillance.nf
  workflows/covidmvp_user.nf
Labels: enhancement, reproducibility, design
